################################################################################
#
# openal
#
################################################################################

OPENAL_VERSION = 1.22.0
OPENAL_SITE = $(call github,kcat,openal-soft,$(OPENAL_VERSION))
OPENAL_LICENSE = LGPL-2.0+
OPENAL_LICENSE_FILES = COPYING
OPENAL_INSTALL_STAGING = YES

# We don't need examples, tests and utilities, Distros don't ship them either
OPENAL_CONF_OPTS += -DALSOFT_UTILS=OFF -DALSOFT_EXAMPLES=OFF -DALSOFT_TESTS=OFF

OPENAL_CONF_OPTS += -DCMAKE_C_FLAGS="-m80387 -mfpmath=387"
OPENAL_CONF_OPTS += -DALSOFT_CPUEXT_SSE:BOOL=OFF -DALSOFT_CPUEXT_SSE2:BOOL=OFF -DALSOFT_CPUEXT_SSE3:BOOL=OFF -DALSOFT_CPUEXT_SSE4_1:BOOL=OFF -DALSOFT_ENABLE_SSE2_CODEGEN:BOOL=OFF 
OPENAL_CONF_OPTS += -DALSOFT_REQUIRE_SSE:BOOL=OFF -DALSOFT_REQUIRE_SSE2:BOOL=OFF -DALSOFT_REQUIRE_SSE3:BOOL=OFF -DALSOFT_REQUIRE_SSE4_1:BOOL=OFF
OPENAL_CONF_OPTS += -DHAVE_MFPMATH_SSE_2:INTERNAL=0 -DHAVE_MSSE2_SWITCH:INTERNAL=0

ifeq ($(BR2_TOOLCHAIN_GCC_AT_LEAST_4_8),y)
OPENAL_CONF_OPTS += -DEXTRA_LIBS=atomic
endif

ifeq ($(BR2_PACKAGE_ALSA_LIB),y)
OPENAL_DEPENDENCIES += alsa-lib
OPENAL_CONF_OPTS += -DALSOFT_REQUIRE_ALSA=ON
else
OPENAL_CONF_OPTS += -DALSOFT_REQUIRE_ALSA=OFF
endif

ifeq ($(BR2_PACKAGE_JACK2),y)
OPENAL_DEPENDENCIES += jack2
OPENAL_CONF_OPTS += -DALSOFT_REQUIRE_JACK=ON
else
OPENAL_CONF_OPTS += -DALSOFT_REQUIRE_JACK=OFF
endif

ifeq ($(BR2_PACKAGE_PORTAUDIO),y)
OPENAL_DEPENDENCIES += portaudio
OPENAL_CONF_OPTS += -DALSOFT_REQUIRE_PORTAUDIO=ON
else
OPENAL_CONF_OPTS += -DALSOFT_REQUIRE_PORTAUDIO=OFF
endif

ifeq ($(BR2_PACKAGE_PULSEAUDIO),y)
OPENAL_DEPENDENCIES += pulseaudio
OPENAL_CONF_OPTS += -DALSOFT_REQUIRE_PULSEAUDIO=ON
else
OPENAL_CONF_OPTS += -DALSOFT_REQUIRE_PULSEAUDIO=OFF
endif

ifeq ($(BR2_STATIC_LIBS),y)
OPENAL_CONF_OPTS += -DLIBTYPE=STATIC
endif

$(eval $(cmake-package))
